### ISSUE TITLE
Reference image for Vahadane normalization

### ISSUE THREAD

**Issue by bswhite** [ncoudray/DeepPATH#139]
Hi @ncoudray,

Thank you for generously sharing your trained models with myself and others. 

I would like to apply these to an external dataset. To do so, it seems I need to normalize my images into the same color space that was used to train them. Would you please share the reference image you used for training the normal/LUAD/LUSC classifier and whether you used Vahadane or Reinhard normalization?  

This is related to a closed issue:
https://github.com/ncoudray/DeepPATH/issues/78

But, again, if I'm not mistaken, we need to use the same "representative" image that you mention in that issue.

Thank you,
Brian

**Comment by ncoudray** [comment]
Hi -

   we used the option "-N '57,22,-8,20,10,5'" to apply the Reinhard normalization. 

Best
N.

**Comment by bswhite** [comment]
Fantastic! Thank you, @ncoudray.
