### ISSUE TITLE
some bugs in your code

### ISSUE THREAD

**Issue by gengyuanzhe** [ncoudray/DeepPATH#18]
Well, in your code, you use `rstrip` to remove the suffix of the string, which may cause some problems. For example,  `imgRootName = imgRootName.rstrip('_files')` of the file "0d_SortTiles.py".
```
>>> 'helle_files'.rstrip('_files')
'h'
```
In this case, the imgRootName will not in the `jdata` map , and the whole dir will not copy to the train-val-test directory.

**Comment by ncoudray** [comment]
Yes, this particular line was corrected ~a month ago. If you pull the latest version, if should be fine. 
Anyway, thanks a lot for pointing that out - I should probably change the one in line 391 too.
