### ISSUE TITLE
Work with .bif .tif images from Ventana software

### ISSUE THREAD

**Issue by Tato14** [ncoudray/DeepPATH#27]
Hi! I am would like to start a project with digital slides scanned from Ventana (Roche). I saw that the preprossesing can manage only svs and jpg files.

Is there any way I could convert the files or modify the code to fit these images in your analysis pipeline?

Thanks!

**Comment by ncoudray** [comment]
Hi,

 I don't know what format is the output of your scanner but you can try. 

 In the pipeline, we do:
1. svs >  tile and convert to jpg 
2. sort jpg such as all jpg with the same label ends up in the same folder (folder name being the label)
3. convert jpg top TFRecord

So you can either convert them to jpg first and order them as needed for TFRecord conversion, or try directly if you can convert whatever format you have to TFRecord (I have never tried, but it might accept png?)

**Comment by Tato14** [comment]
Hi @ncoudray, thanks for the reply. 

The bif format is similar to the svs from Aperio (but from Roche's Ventana software). 

Actually I am most interested in the tile strategy that you modified form the openslide deepzoom_tile.py. Openslide-python could manage bif files. 

My question would be, is there any change that I could do to use your "0b_tileLoop_deepzoom4.py" to accept bif files as input?

Thanks again :)

**Comment by ncoudray** [comment]
Just try and see if there is any error message! If you look at the openslide webpage, it says it does accept bif (https://openslide.org/).

**Comment by ncoudray** [comment]
BTW, please let me know if it worked or not. Don't forget do let the program know you're using bif (when specifying to path to the images, for example: '/path_to_images/*bif' )

**Comment by Tato14** [comment]
Hi @ncoudray 

Well I have not enough words to express my hype right now but IT WORKED AT THE FIRST TRY. I used the example from openslide (http://openslide.cs.cmu.edu/download/openslide-testdata/Ventana/). Have to manage the background issue because I got tiles without any sample, however.

The command, just for reporting purposes (I am using it in my local machine):

python /home/jgibert/0b_tileLoop_deepzoom.py  -s 299 -e 0 -j 2 -B 25 -o /path/to/output/ "/path/to/input/*bif"

I will try the cluster in the following days with more samples (we do not have GPUs at the moment) to keep track of the issue.

Thanks!

**Comment by ncoudray** [comment]
Great!
BTW, for tiles without sample, you can use the "-B 25" option (you may change the 25% threshold according to your needs. The default threshold to choose what the "background" is is hard-coded and can be changed in line 84 and 87 of 0b_tileLoop_deepzoom4.py (default is a grey level of 220)
