### ISSUE TITLE
Normal tissue whole slide images

### ISSUE THREAD

**Issue by Tato14** [ncoudray/DeepPATH#29]
I cannot find them nor in the GDC page neither in the legacy one. Any idea where I could find them?

Thanks!

**Comment by ncoudray** [comment]
You need to look at the metadata file. They are labelled "Solid Normal Tissue"
This for example:
https://portal.gdc.cancer.gov/files/10d57245-6a52-443f-acfa-65a8b00af5a2

They are usually labelled TCGA-##-####-11

**Comment by Tato14** [comment]
Thank you! Of note, all the "Solid Normal Tissue" that I found are from fresh frozen, not FFPE. That was the reason you used the frozen tissue samples in your study? :-)

**Comment by ncoudray** [comment]
No - they were just not part of the legacy portal, as far as I remember.
