### ISSUE TITLE
Removal of ~empty slides

### ISSUE THREAD

**Issue by bcli4d** [ncoudray/DeepPATH#30]
In the preprint of your paper, you state that  "The slides with a low amount of information
were removed, that is all the tiles where more than 50% of the surface is covered by background (where all the values are below 220 in the RGB color space). " I don't see this happening in the tiling code (v0b_tileLoop_deepzoom4.py). 
Did I miss it, or did you determine that culling such images is not important? 

Thanks for making this very interesting work available.

**Comment by ncoudray** [comment]
Hi.

See lines 84 to 87 of the code

Best,
Nicolas

**Comment by bcli4d** [comment]
Nicolas,
I interpreted the above quote to say that entire slides are removed if more the 50% of the slide is background.  Should that sentence really have said  "The **tiles** with a low amount of information
were removed,..." ? 
Thanks,
Bill

**Comment by bcli4d** [comment]
By the way, I suggest changing line 89 of v0b_tileLoop_deepzoom4.py:
`if avgBkg <= (self._Bkg / 100):`
to
`if avgBkg <= (self._Bkg / 100.0):`
It appears that the argument parser doesn't coerce the --Background argument to a float when the specified argument value "looks" like an integer, e.g. "50", and even though the argument type is declared to be float. This results in integer division, which produces a value of 0 or 1.

**Comment by ncoudray** [comment]
Thanks for the feedback.
Indeed, only the tiles are removed
