### ISSUE TITLE
Validation and testing questions

### ISSUE THREAD

**Issue by bcli4d** [ncoudray/DeepPATH#32]
Hello,

I've run through all the steps except for generating the ROC curves, and have a few questions on interpreting results that I am hoping you can help me with.
More specifically to what I've done: I tiled all .svs files only for 5x magnification, and have only performed transfer learning (on Inception v3), for 10,000 batches of 30 tiles. Classifying for normal, LUAD and LUSC. 

Running on a Google VM with a single K80 GPU. 

1. During validation, nc_imagenet_eval.py appears to complete successfully, but reports the following for each image in the validation set:
`ERROR: Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'init' type=NoOp>
If you want to mark it as used call its "mark_used()" method.`
There are multiple reports of this error on stackoverflow, but no solution that I can find. Have you encountered this? I'm running tensorflow-gpu 1.13.1. 

2. As I mentioned, validation does seem to complete successfully, generating these five AUC files:
::::::::::::::
valid_out2_AvPb_AUCs_1.txt
::::::::::::::
/mnt/disks/deeppath-data/Data/images/tilings/299Px0Ol25Bg5Mg/eval results/ 10000 auc 0.9758 CIs 0.9517 0.9942 t0.127599
::::::::::::::
valid_out2_AvPb_AUCs_2.txt
::::::::::::::
/mnt/disks/deeppath-data/Data/images/tilings/299Px0Ol25Bg5Mg/eval results/ 10000 auc 0.9493 CIs 0.9218 0.9712 t0.573981
::::::::::::::
valid_out2_AvPb_AUCs_3.txt
::::::::::::::
/mnt/disks/deeppath-data/Data/images/tilings/299Px0Ol25Bg5Mg/eval results/ 10000 auc 0.9641 CIs 0.9411 0.9815 t0.437919
::::::::::::::
valid_out2_AvPb_AUCs_macro.txt
::::::::::::::
/mnt/disks/deeppath-data/Data/images/tilings/299Px0Ol25Bg5Mg/eval results/ 10000 auc 0.9654 CIs 0.9455 0.9795
::::::::::::::
valid_out2_AvPb_AUCs_micro.txt
::::::::::::::
/mnt/disks/deeppath-data/Data/images/tilings/299Px0Ol25Bg5Mg/eval results/ 10000 auc 0.9496 CIs 0.9329 0.9632
Can you explain what these are about? I presume the first three files correspond to Normal, LUAD and LUSC respectively. What are the macro and micro files, and what are the CI and t values?

3. The file out_filename_Stats.txt that is generated by nc_imagenet_eval.py during testing seems to repeat the evaluation for each tile multiple times, e.g.:
test_TCGA-58-8386-11A-01-TS1.7276c7ee-44c5-45e8-a8cd-1e456dc4795f_3_4.dat	True	[0.02668606 0.7224843  0.20596845 0.04486124]	0.7422931346515897	labels: 	1
test_TCGA-58-8386-11A-01-TS1.7276c7ee-44c5-45e8-a8cd-1e456dc4795f_3_5.dat	True	[0.01350667 0.9084061  0.06515231 0.01293499]	0.9208435613386187	labels: 	1
test_TCGA-58-8386-11A-01-TS1.7276c7ee-44c5-45e8-a8cd-1e456dc4795f_3_6.dat	True	[0.02568119 0.62040573 0.24854586 0.10536721]	0.6367584581442096	labels: 	1
test_TCGA-58-8386-11A-01-TS1.7276c7ee-44c5-45e8-a8cd-1e456dc4795f_4_6.dat	False	[0.03846446 0.29852733 0.4035099  0.25949836]	0.31046934641665214	labels: 	1
test_TCGA-58-8386-11A-01-TS1.7276c7ee-44c5-45e8-a8cd-1e456dc4795f_3_4.dat	True	[0.0266861  0.722484   0.20596856 0.04486128]	0.7422929477823531	labels: 	1
test_TCGA-58-8386-11A-01-TS1.7276c7ee-44c5-45e8-a8cd-1e456dc4795f_3_5.dat	True	[0.01350666 0.908406   0.0651524  0.01293498]	0.9208434861390423	labels: 	1
test_TCGA-58-8386-11A-01-TS1.7276c7ee-44c5-45e8-a8cd-1e456dc4795f_3_6.dat	True	[0.02568119 0.62040573 0.24854586 0.10536721]	0.6367584581442096	labels: 	1
test_TCGA-58-8386-11A-01-TS1.7276c7ee-44c5-45e8-a8cd-1e456dc4795f_4_6.dat	False	[0.03846446 0.29852733 0.4035099  0.25949836]	0.31046934641665214	labels: 	1
 ... etc
The above file, for example, is repeated 75 times. What are these repetitions about? And can you explain the three values in brackets?

Thanks as always.
Bill

**Comment by ncoudray** [comment]
Hi,

 1- I haven't seen this error, sorry.

 2- Those files just summarize whatever is in the test_####k folders. You should have 1 folder per checkpoint saved. It looks like in your case, you only have the 10000 iteration saved or available. This summary is only done for the "out2*" files (meaning per slide averages), for first 3 labels, macro and micro averages. They show the AUC and CIs. It's just a summary but you can change the code easily if you need to extract other info. Labels "1", "2" and "3" would be whatever order was in your "sorted" folder (before conversion to TFRecord), in alphabetical order.

  3- These are the probabilities generated for each tile. You have the tile name and in the brackets, the probabilities generated for the 3 classes (you have an additional class (the first one) called the "background" class which is part of the original inception). The number after the bracket is the corrected probability (ignoring the background class) for the expected label. 

HTH
N.

**Comment by bcli4d** [comment]
Thanks. 

Bill

**Comment by bcli4d** [comment]
The error that I described above is fixed by changing line 66 in nc_inception_eval.py from:
`tf.initialize_all_variables()`
to
`tf.global_variables_initializer()`
ref. [here](https://www.tensorflow.org/api_docs/python/tf/initialize_all_variables). initialize_all_variables() is deprecated and apparently is broken in newer tensorflow releases.

Bill

**Comment by ncoudray** [comment]
Thanks for the follow up, Bill.

**Comment by bcli4d** [comment]
I am encountering additional errors in attempting to train for mutation classification using ...01_training/xClasses/bazel-bin/inception/imagenet_train (output below).  I am presuming it is a similar deprecation issue. I'm running tensorflow-gpu 1.13.1 for compatibility with the latest CUDA. I encountered many issues trying to install earlier CUDA versions.

Anyway...in investigating this I looked at the TFRecords being generated. A typical label component is:
>   feature {
>     key: "image/class/label"
>     value {
>       int64_list {
>         value: 0
>         value: 1
>         value: 0
>         value: 0
>         value: 0
>         value: 0
>         value: 0
>         value: 0
>         value: 0
>         value: 1
>         value: 1
>       }
>     }

Notice that there are 11 values, but we have ten labels.  Is this as expected? The first value in the record is ignored?
Also, a typical filename component is:
>   feature {
>     key: "image/filename"
>     value {
>       bytes_list {
>         value: "train_TCGA-86-8280-01A-01-TS1.03ddd678-176c-4608-89e6-4f8ee6de5cc4_21_15.jpeg"
>       }
>     }
>   }
> 
>
I.E. the filename is not a full path to the file, nor does parameterization of imagenet_train include such a path. So where is imagenet_train getting that path?

Thanks,
Bill

Partial output from failing multiclass training:
`
WARNING:tensorflow:From /home/bcliffor/DeepPATH/DeepPATH_code/01_training/xClasses/bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_train.py:339: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
2019-04-29 16:14:14.696263: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2019-04-29 16:14:24.091919: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/class/label.  Can't parse serialized Example.
2019-04-29 16:14:24.091920: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/class/label.  Can't parse serialized Example.
2019-04-29 16:14:24.091920: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/class/label.  Can't parse serialized Example.
2019-04-29 16:14:24.091935: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: image/class/label.  Can't parse serialized Example.
ERROR:tensorflow:Exception in QueueRunner: Key: image/class/label.  Can't parse serialized Example.
	 [[{{node batch_processing/ParseSingleExample_1/ParseSingleExample}}]]
ERROR:tensorflow:Exception in QueueRunner: Key: image/class/label.  Can't parse serialized Example.
	 [[{{node batch_processing/ParseSingleExample/ParseSingleExample}}]]
ERROR:tensorflow:Exception in QueueRunner: Key: image/class/label.  Can't parse serialized Example.
	 [[{{node batch_processing/ParseSingleExample_2/ParseSingleExample}}]]
ERROR:tensorflow:Exception in QueueRunner: Key: image/class/label.  Can't parse serialized Example.
	 [[{{node batch_processing/ParseSingleExample_3/ParseSingleExample}}]]
Exception in thread QueueRunnerThread-batch_processing/batch_join/fifo_queue-batch_processing/batch_join/fifo_queue_enqueue_3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bcliffor/dp/lib/python3.5/site-packages/tensorflow/python/training/queue_runner_impl.py", line 257, in _run
    enqueue_callable()
  File "/home/bcliffor/dp/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1257, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/home/bcliffor/dp/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Key: image/class/label.  Can't parse serialized Example.
	 [[{{node batch_processing/ParseSingleExample_3/ParseSingleExample}}]]

Exception in thread QueueRunnerThread-batch_processing/batch_join/fifo_queue-batch_processing/batch_join/fifo_queue_enqueue_1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bcliffor/dp/lib/python3.5/site-packages/tensorflow/python/training/queue_runner_impl.py", line 257, in _run
    enqueue_callable()
  File "/home/bcliffor/dp/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1257, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/home/bcliffor/dp/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Key: image/class/label.  Can't parse serialized Example.
	 [[{{node batch_processing/ParseSingleExample_1/ParseSingleExample}}]]`

**Comment by ncoudray** [comment]
Hi,

 There is an extra "background" class in inception, so an additional one will be automatically added during the processing (you can check the original github page: https://github.com/tensorflow/models/blob/master/research/inception/README.md)

 Just be careful also when you convert to TFRecord. You can double check everything is fine with the name of the test TFRecord files. the "true" label appears as a binary at the end of the file name. If you have 10 labels, the label text file must have exactly 10 lines (no empty line at the top or at the bottom)

HTH,
Best,
Nicolas

**Comment by bcli4d** [comment]
Hello Nicolas,

I finally realized that the mode must be sigmoid not softmax when doing
multiclass. I didn't understand that the README, "The mode option must be
set to either 0_softmax (original inception - only one ouput label
possible) or 1_sigmoid (several output labels possible)', was telling me
this, though it is clear in hindsight.

One more question: There is a multiClasses/nc_imagenet_eval.py. Should it
be used for multiclass validation/testing instead of
xClasses/nc_imagenet_eval.py? xClasses/nc_imagenet_eval.py seems to work on
multiclass TF records.

Thanks as always,
Bill

**Comment by ncoudray** [comment]
Hi - Glad this is solved.

I indeed used "multiClasses/nc_imagenet_eval.py" originally, but the "xClasses/nc_imagenet_eval.py" should work too (if you use that one, you would need to add the " --mode='1_sigmoid'" option). 
At some I will probably delete the "multiClasses/nc_imagenet_eval.py"  from the code and just keep the second xClass version.

Best,
Nicolas
