### ISSUE TITLE
Configuration Requirement

### ISSUE THREAD

**Issue by itszhengan** [ncoudray/DeepPATH#33]
Hi, I want to use your model to train my dataset.  Is there any hardware requirement, such as GPU, CPU or Memory size?  Everytime I want to test my trained model,  my computer crashes. So could you please tell me your hardware parameters, particularly Memory size？ Thank you.

**Comment by ncoudray** [comment]
Hi An,

 Here is an example of GPU we are using:
25 x Cray CS-Storm 500NX

    2x Skylake 6148, 20-core, 2.4GHz, 150W processors
    12x 32GB DDR4-2666 DIMMs (DUAL RANKED) , 384 GB/node, 9.6 GB/core
    4 NVIDIA® Tesla V100 GPUs
    GPU-to-GPU NVLINK
    GPUDirect RDMA
    2x 2TB 2.5” SATA HDD
    2x 2TB NVMe SSD
    1x EDR 100Gb/s Infiniband network interface for MPI and Data traffic

HTH,
Best,
Nicolas

**Comment by itszhengan** [comment]
Thank you Nicolas.


Best,
Zheng An

Nicolas Coudray <notifications@github.com> 于2019年5月20日周一 下午9:00写道：
