### ISSUE TITLE
The problem of images ,corresponding JSON and xml files download

### ISSUE THREAD

**Issue by BaldwinHe** [ncoudray/DeepPATH#39]
Hi, sorry to interrupt.

As shown in the first image, I have tried a lot to download the file from [https://portal.gdc.cancer.gov/legacy-archive/search/f](https://portal.gdc.cancer.gov/legacy-archive/search/f).
<img width="1277" alt="屏幕快照 2019-07-24 下午2 54 09" src="https://user-images.githubusercontent.com/32444886/61772454-e6751800-ae24-11e9-9244-74c49c3251ee.png">
When I try to test the code, `0.1 Tile the svs slide images` works well, but it seems that `0.2 Sort the tiles into train/valid/test sets according to the classes defined` fails, which is shown in the second image.
<img width="738" alt="屏幕快照 2019-07-24 下午3 09 04" src="https://user-images.githubusercontent.com/32444886/61772503-0c022180-ae25-11e9-9e7a-d86f0da3d0af.png">
I think I downloaded the wrong images, xml, and JSON files when the website has changed a lot.

Could you help me to find the data you use in this program? 

Thanks a lot for your kindness!

**Comment by ncoudray** [comment]
Hi - It don't understand your issue: to me, it looks fine: it looks like you downloaded only 2 svs images, so when it sort them, it assigned them to the valid set, but if you want something in the train and test, you need to download more than 2 images. You can do it by downloading metadata and then using their gdc-client, it's faster than doing them one by one.

HTH,
Nicolas
