### ISSUE TITLE
Step 0.2 File Clarification

### ISSUE THREAD

**Issue by stevedough123** [ncoudray/DeepPATH#41]
Hi,
I'm trying to run step 0.2 and sort my tiles. However, there was one step I am confused about.

"--SortingOption. In the current directory, create one sub-folder per class, and fill each sub-folder with train_, test_ and valid_ test files. Images will be sorted into classes depending on the sorting option."

What does this mean? What is my current directory, and what are the train_, test_, and valid_ files?
Sorry if this is a bad question; I am fairly new to this type of programming.

**Comment by steermomo** [comment]
Your current directory is the directory path where you run the command

**Comment by stevedough123** [comment]
@steermomo Okay, what about the train_, test_, and valid_ files?

**Comment by steermomo** [comment]
![](http://ww1.sinaimg.cn/large/dd456925ly1g5d96hzjs1j20q408smxk.jpg)

**Comment by stevedough123** [comment]
@steermomo got it, thank you! Also, just a general question, I'm running the script through Windows terminal. Is there another way to run the script, because the terminal is very inconvenient?

**Comment by steermomo** [comment]
@stevedough123  I'm running the code on an ubuntu server via ssh.
