### ISSUE TITLE
How to select Hugo Symbol from mutation file?

### ISSUE THREAD

**Issue by steermomo** [ncoudray/DeepPATH#43]
Hi Nicolas, 

I've downloaded the mdf file. Tiles are generated at 20X, 299 pixels, 0 overlap, 25% background threshold.

Currently, the Hugo Symbol is chosen by  "Variant_Classification", I only select the Hugo Symbol which is in ['Missense_Mutation', 'Nonsense_Mutation', 'Frame_Shift_Del', 'Frame_Shift_Ins'], but the performance only slightly better than #37 .

I want to know the correct way to use the mutation file. Did you use all the Hugo Symbol that appears in the mdf file?
 
Many thanks!

**Comment by ncoudray** [comment]
Hi,

   I will post more details soon. 

Thanks for your patience,
Best,
Nicolas

**Comment by steermomo** [comment]
Very appreciate for that : )

**Comment by ncoudray** [comment]
Hi - it is explained in the middle of the example page (https://github.com/ncoudray/DeepPATH/tree/master/DeepPATH_code/example_TCGA_lung)

Best

**Comment by Reasat** [comment]
Hi @ncoudray 
Thanks for the reply! In the description, it says "_Retrieve the mutation information from the GDC website._ ". Are these the .vcf files associated with each of the cases?

**Comment by ncoudray** [comment]
I think the maf formats were used, and the maftools in
https://bioconductor.org/packages/release/bioc/html/maftools.html
