### ISSUE TITLE
How do you install Bazel?

### ISSUE THREAD

**Issue by stevedough123** [ncoudray/DeepPATH#45]
Having difficulty using bazel-bin. I've tried everything on the bazel website,  still no luck.

**Comment by steermomo** [comment]
You don't need to install bazel, just run it as python file.

**Comment by steermomo** [comment]
Actually, it may occur some problem when you training the network. You can put an empty `__init__.py` file in 01_training/xClasses/inception directory, and train the network like this way
```python
cd DeepPATH/DeepPATH_code/01_training/xClasses

python -m inception.imagenet_train --num_gpus=4 --batch_size=200 --train_dir=xxxx --data_dir=xxxx --ClassNumber=3 --model='0_softmax' --max_steps=100000
```
