### ISSUE TITLE
Issue with bazel-bin

### ISSUE THREAD

**Issue by stevedough123** [ncoudray/DeepPATH#46]
I get the following error, which says I don't have the inception module:
<img width="959" alt="error3" src="https://user-images.githubusercontent.com/52977783/62394784-13ab7f80-b523-11e9-8d34-97d9e2c9c298.png">
Any idea how to fix this?

**Comment by ncoudray** [comment]
Hi,

It needs to either be in your path or in the folder from which you're running it

Best
N.

**Comment by stevedough123** [comment]
> Hi,
> 
> It needs to either be in your path or in the folder from which you're running it
> 
> Best
> N.

Hi, I have already tried that but it still does not work.

**Comment by ncoudray** [comment]
Are you on a linux machine?

Best,
N.

**Comment by stevedough123** [comment]
No, I am using Windows. Should I use Linux?

**Comment by ncoudray** [comment]
I've never run it on Windows, so I can't help. We're using Linux.

**Comment by wwegami** [comment]
Now I have exactly the same problem on Windows 10. Already solved this after that?
