### ISSUE TITLE
Validation step does not output "out_filename_Stats.txt"

### ISSUE THREAD

**Issue by mattreex** [ncoudray/DeepPATH#49]
Code is run on aws ec2 p3.16xlarge instance, ami-004852354728c0e51. 

There seems to be an issue with the output generated by the validation step when the following code is run. Code does not work if absolute path is used. Only works if relative path is used. This is true for preprocessing steps as well. 

````
export CHECKPOINT_PATH='./t3_results'
export OUTPUT_DIR='./r1_valid'
export DATA_DIR='./TF_valid'
export LABEL_FILE='./labels.txt'
# create temporary directory for checkpoints
mkdir -p $OUTPUT_DIR/tmp_checkpoints
export CUR_CHECKPOINT=$OUTPUT_DIR/tmp_checkpoints
# check if next checkpoint available
declare -i count=1300
declare -i step=1300
declare -i NbClasses=2
 while true; do
	echo $count
	if [ -f $CHECKPOINT_PATH/model.ckpt-$count.meta ]; then
		echo $CHECKPOINT_PATH/model.ckpt-$count.meta " exists"
		# check if there's already a computation for this checkpoinmt
		export TEST_OUTPUT=$OUTPUT_DIR/test_$count'k'
		if [ ! -d $TEST_OUTPUT ]; then
			mkdir -p $TEST_OUTPUT
			
			ln -s $CHECKPOINT_PATH/*-$count.* $CUR_CHECKPOINT/.
			touch $CUR_CHECKPOINT/checkpoint
			echo 'model_checkpoint_path: "'$CUR_CHECKPOINT'/model.ckpt-'$count'"' > $CUR_CHECKPOINT/checkpoint
			echo 'all_model_checkpoint_paths: "'$CUR_CHECKPOINT'/model.ckpt-'$count'"' >> $CUR_CHECKPOINT/checkpoint
			# Test
                        echo "Now entering Imagenet_eval"
			python 02_testing/xClasses/nc_imagenet_eval.py --checkpoint_dir=$CUR_CHECKPOINT --eval_dir=$OUTPUT_DIR --data_dir=$DATA_DIR 
   --mode='0_softmax' --TVmode='test'
			# wait
			mv $OUTPUT_DIR/out* $TEST_OUTPUT/.
			# ROC
			export OUTFILENAME=$TEST_OUTPUT/out_filename_Stats.txt
                        echo "Now entering BootStrap"
			python 03_postprocessing/0h_ROC_MultiOutput_BootStrap.py --file_stats=$OUTFILENAME --output_dir=$TEST_OUTPUT 

		else
			echo 'checkpoint '$TEST_OUTPUT' skipped'
		fi
	else
		echo $CHECKPOINT_PATH/model.ckpt-$count.meta " does not exist"
		break
	fi
	# next checkpoint
	count=`expr "$count" + "$step"`
done
````
The error received:
![Screenshot from 2019-09-09 13-05-05](https://user-images.githubusercontent.com/45504048/64557795-f29b3300-d307-11e9-98e5-93a1f20dd1b5.png)

 Only one file for each checkpoint is being generated `out_All_stats.txt`. The `0h_ROC_MultiOutput_BootStrap.py` script is trying to retrieve `out_filename_Stats.txt` but this file is never generated by `nc_imagenet_eval.py`. 

Contents of directories: 
![Screenshot from 2019-09-09 13-42-52](https://user-images.githubusercontent.com/45504048/64557826-021a7c00-d308-11e9-9d8f-89453a705649.png)

**Comment by ncoudray** [comment]
Hi -

  I would actually advise to replace all paths with full absolute paths. 
 Also, it looks like "--mode='0_softmax' --TVmode='test" is starting on a new line in your code. It is not a new line, it is an option of the previous line of the code, the "nc_imagenet_eval.py"

Best,
Nicolas

**Comment by mattreex** [comment]
Hi Nicolas,
Thank you for your prompt response. Full paths seem to give the same error. --mode and -TVmode are on one line in actual script. 
![Screenshot from 2019-09-09 16-03-03](https://user-images.githubusercontent.com/45504048/64566410-8d513d00-d31b-11e9-9b42-9f416608acb8.png)

In the output ````/home/ubuntu/TF_valid/test_*```` is printed. It's not clear why this output is being generated.

**Comment by ncoudray** [comment]
If the script sent above is the one submitted then part of the options are on a new line instead of in the same as the code. Furthermore, some options of the "nc_imagenet_eval.py" are missing. Please double check carefully and compare with the one posted on the README files

**Comment by mattreex** [comment]
Indeed the wrong script was being used. Thank you.
