### ISSUE TITLE
validation error - cannot generate "out_filename_Stats.txt"

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [ncoudray/DeepPATH#51]
Hi Nicholas,
I was running validation for classification of lung cancer into three types - normal, LUAD, and LUSC. The command was shown as in the two following screenshot:
![Screen Shot 2019-09-26 at 5 23 37 PM](https://user-images.githubusercontent.com/9053403/65676436-7d0ec100-e082-11e9-98ea-e0627b34f871.png)
![Screen Shot 2019-09-26 at 5 23 49 PM](https://user-images.githubusercontent.com/9053403/65676439-7e3fee00-e082-11e9-8b34-b039609bcbab.png)

However, there was an error message like below:
![Screen Shot 2019-09-26 at 5 25 12 PM](https://user-images.githubusercontent.com/9053403/65676507-9e6fad00-e082-11e9-84e1-904698d425f0.png)

My training command is shown below using step size of 2300:
~/tools/DeepPATH-master/DeepPATH_code/01_training/xClasses/bazel-bin/inception/imagenet_train --num_gpus=4 --batch_size=32 --train_dir='/public/home/yangzhzh/projects/imaging/3_training/r1_results' --data_dir='/public/home/yangzhzh/projects/imaging/2_preprocessing/r1_TFRecord_train' --ClassNumber=3 --mode='0_softmax' --NbrOfImages=923688 --save_step_for_chekcpoint=2300 --max_steps=230001

I figured the error likely results from "nc_imagenet_eval.py". So I submitted the job locally for one checkpoint only with command shown below:

python ~/tools/DeepPATH-master/DeepPATH_code/02_testing/xClasses/nc_imagenet_eval.py  --checkpoint_dir='/public/home/yangzhzh/projects/imaging/4_validation/r1_valid/tmp_checkpoints' --eval_dir='/public/home/yangzhzh/projects/imaging/4_validation/r1_valid' --data_dir='/public/home/yangzhzh/projects/imaging/2_preprocessing/r1_TFRecord_valid'  --batch_size 300  --run_once --ImageSet_basename='valid_' --ClassNumber 3 --mode='0_softmax'  --TVmode='test'

And I got error message like below:
New Slide ------------ 0
label 3: label_3
tf_record_pattern:
/public/home/yangzhzh/projects/imaging/2_preprocessing/r1_TFRecord_valid/valid_TCGA-60-2711-01A-01-BS1.2591160e-4240-41ba-a7ef-38f7b135313e_3.TFRecord
['/public/home/yangzhzh/projects/imaging/2_preprocessing/r1_TFRecord_valid/valid_TCGA-60-2711-01A-01-BS1.2591160e-4240-41ba-a7ef-38f7b135313e_3.TFRecord']
tf_record_pattern:
/public/home/yangzhzh/projects/imaging/2_preprocessing/r1_TFRecord_valid/valid_TCGA-60-2711-01A-01-BS1.2591160e-4240-41ba-a7ef-38f7b135313e_3.TFRecord
['/public/home/yangzhzh/projects/imaging/2_preprocessing/r1_TFRecord_valid/valid_TCGA-60-2711-01A-01-BS1.2591160e-4240-41ba-a7ef-38f7b135313e_3.TFRecord']
/public/home/yangzhzh/projects/imaging/2_preprocessing/r1_TFRecord_valid/valid_TCGA-60-2711-01A-01-BS1.2591160e-4240-41ba-a7ef-38f7b135313e_3.TFRecord FAILED to be processed properly

In the "nc_imagenet_eval.py" script, there is a block of code which shows how this may be caused:

![Screen Shot 2019-09-26 at 5 27 54 PM](https://user-images.githubusercontent.com/9053403/65676770-0de59c80-e083-11e9-9d9c-dcc24dc99f0a.png)

So I am guessing the error is likely because the following condition failed:
try:
    precision_at_1, current_score = nc_inception_eval.evaluate(dataset)

Could you perhaps know why the valid_*.TFRecord failed to be processed properly?

Thanks very much.
Zhenzhen

**Comment by ncoudray** [comment]
Hi Zhenzhen,

  double check that the corresponding checkpoints (3 files per checkpoint) are indeed created in the /public/home/yangzhzh/projects/imaging/3_training/r1_results directory and that the symlink in the '/public/home/yangzhzh/projects/imaging/4_validation/r1_valid/tmp_checkpoints'  folders are properly created

HTH,
Best,
Nicolas

**Comment by zhenzhenyang-psu** [comment]
Hi Nicolas,
Thanks for your reply.
Yes, the checkpoints file and symbolic links have been properly created, as shown below.
![Screen Shot 2019-10-08 at 11 45 51 AM](https://user-images.githubusercontent.com/9053403/66366117-f7640d00-e9c1-11e9-8b1a-8ca9607656cc.png)
![Screen Shot 2019-10-08 at 11 47 39 AM](https://user-images.githubusercontent.com/9053403/66366120-f92dd080-e9c1-11e9-80e9-d331e476625b.png)

I reran everything yet this error still remains. 
I tried your pipeline in bladder cancer by classifying two subtypes - just normal and tumor, it succeeded (training, validation and testing all succeeded). I have no idea why it failed with lung cancer. 
Thanks,
Zhenzhen

**Comment by ncoudray** [comment]
Weird indeed. If it worked with bladder, there's no reason it wouldn't work for lung. Check the permissions, or maybe if that file was somehow corrupted....

Maybe you can catch the error or comment out the "try / except" to see where the error comes from

**Comment by mattreex** [comment]
If you ran build_TF_test.py to create the validation TFrecords with num_threads > 1, you may have created some corrupted TFRecords which can be a pain to identify.

**Comment by ncoudray** [comment]
Indeed, I noticed that too. I'll add that information to the README file. Thanks.

**Comment by zhenzhenyang-psu** [comment]
thanks very much, that is indeed very tricky!

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zhenzhenyang-psu** [comment]
hi sorry, I forgot to update about the error. I later found that this is because I submitted the job to a node in which GPU was not install properly. thanks!
