### ISSUE TITLE
3-way classifier

### ISSUE THREAD

**Issue by MarkLeePro** [ncoudray/DeepPATH#52]
Hi,
I have a question about the step of 3-way classifier.
when I run code as the example of lung cancer（run 0d_SortTiles.py --SourceFolder='E:/marklee/master/git/DeepPATH/DeepPATH_code/preprocessing/512px_Tiled' --Magnification=20.0  --MagDiffAllowed=0 --SortingOption=3  --PatientID=12 --nSplit 0 --JsonFile='D:/evi/downloads/lung10.29/metadata.cart.2019-10-29.json' --PercentTest=15 --PercentValid=15）,it will error as the following image.
![20191029184239](https://user-images.githubusercontent.com/50647103/67760291-00557500-fa7c-11e9-9b2c-1a79c73b60f5.png)
Could you help me to solve this problem?Thank you very much.

**Comment by MarkLeePro** [comment]
My python version is 3.6,Will this have an impact on this error?

**Comment by ncoudray** [comment]
Hi Mark,

  Maybe try to put it in the same drive where your code is run (E). Alternatively, you can write a small script in python to make sure it can be open properly and it's not a drive access issue

N.

**Comment by MarkLeePro** [comment]
Hi Nicholas,
Thanks for your reply.I have completed this step by your help.Thanks a lot.

**Comment by ncoudray** [comment]
You're welcome.
