### ISSUE TITLE
Checkpoint Data Missing

### ISSUE THREAD

**Issue by jeremykap** [ncoudray/DeepPATH#54]
Hello!

I'm a graduate student doing a class project on what it would take to bring machine learning models from the lab to the clinic, and was hoping to leverage your work here as a useful case studies as a well built out model. We were hoping to use some of your existing models on some augmented data, but it seems like the actual data files are missing from the DeepPATH_code/example_TCGA_lung/checkpoints directory. Given the computational cost to retrain some of these models, would it be possible for you to share the complete checkpoints?

**Comment by ncoudray** [comment]
Hi Jeremy,

 Indeed, the file is too big to be posted there. Please email me a link to a server or a safe place where I can share it with you and where there's enough space (~1.5)

Best,
Nicolas

**Comment by jeremykap** [comment]
Can you reach out to me in the email in my GitHub profile? Can’t seem to find your email publicly, but I have a drop box you can upload them to.

Thanks,
Jeremy
