### ISSUE TITLE
Issue about Gene mutation prodiction

### ISSUE THREAD

**Issue by yundumbledore** [ncoudray/DeepPATH#55]
Hi,

We are doing relatively the same job as yours. In particular, we wanna reproduce the case studies in your Nature paper. I have several concerns about gene mutation prediction on LUAD. We have all data from TCGA and we are currently using pytorch. We used the same experimental setups you mentioned in your Nature paper. We tried 4 months but failed to obtain the model performance you demonstrated. After reviewing your paper, I found some strange points. Now, I would like to ask you. 

- Can you give us a comprehensive description of gene mutation prediction? Including all parameters and operations. The description in your Nature paper is not detailed so far for me. Cause we cannot use that to reproduce your work.

- You mentioned that you used the label from TCGA and tested your model using the results given by LUAD classifier. I'm a little confused. Why you did not keep things consistent? To me, it makes sense that you use TCGA labels in training and testing.

Rowen
13/12/2019

**Comment by ncoudray** [comment]
Hi Rowen,

  Regarding more details about the steps, you can check:
https://github.com/ncoudray/DeepPATH/tree/master/DeepPATH_code/example_TCGA_lung

  We now favor the use of binary classifier over multi-class sigmoid classifier. You can see an example at the end of this thread:
https://github.com/ncoudray/DeepPATH/issues/37

 Regarding your second point, the reason we selected a subset of slides among LUAD tiles is to compute the analysis only on tiles that are classified as LUAD with a high probability, therefore reducing the chance of using regions with normal cells.

Best,
Nicolas

**Comment by yundumbledore** [comment]
Hi,

I do agree with you for the second point.:)

It makes sense that binary classifier is easy to obtain. But I'm more concerned about the multi-label classification. 

Anyway, thank you and your paper.

Regards,
Rowen
