### ISSUE TITLE
How to get the ROC curve

### ISSUE THREAD

**Issue by MarkLeePro** [ncoudray/DeepPATH#56]
Hi,
I have run the code 0h_ROC_MultiOutput_BootStrap.py,and get txt as following photo,how can I get the ROC curve？
Thanks,
Mark
![image](https://user-images.githubusercontent.com/50647103/72245898-84a3a700-362c-11ea-97a3-403ab99f14ac.png)

**Comment by ncoudray** [comment]
Hi Mark,

  out1* files are statistics per tile, out2* per slide, and out3* per patients if fields are properly given. 
 To plot roc curves, check data within out*_roc_*. There should be 2 columns that can be used to plot the ROC curve

HTH,
Best,
Nicolas

**Comment by MarkLeePro** [comment]
I get it,thanks!
