### ISSUE TITLE
Typo on example_TCGA_lung/checkpoints/README.md

### ISSUE THREAD

**Issue by imxiaow** [ncoudray/DeepPATH#58]
The class label stated for run1a_3D_classifier and run2a_3D_classifier checkpoint is:  Normal/LUAD/LUAD. 
Isn't this should be: Normal/LUAD/LUSC?
Since these checkpoints are using class labels from example_TCGA_lung/labelref_r1.txt

Regards,
Xiao

**Comment by ncoudray** [comment]
Yes, it's a typo - thanks
Best,
Nicolas
