### ISSUE TITLE
Use 0b_tileLoop_deepzoom4.py to only get tile coordinates

### ISSUE THREAD

**Issue by Tato14** [ncoudray/DeepPATH#59]
Hi, 
I am not quite familiar wih openslide code, so apologizes if this is kind of a trivial question. I would like to get only the coordinates where I could find tissue but I don't want to create tiles _per se_ for the WSI. Could I use `0b_tileLoop_deepzoom4.py` for it? Getting file names of the tiles would suffice. 
Thanks

**Comment by ncoudray** [comment]
Hi -
Sorry, not sure I understand the question. To get coordinates, then you would need to open the svs files with another program. Maybe Imagescope, or ImageJ (with Bio-Formats plugin)
HTH,
Best,
Nicolas
