### ISSUE TITLE
Model checkpoints missing data file

### ISSUE THREAD

**Issue by andanison** [ncoudray/DeepPATH#60]
Hi 

I am trying to use the model checkpoints to try to predict on a new patch/image. Generally for each checkpoint we have three files: meta file, index file, data file. However for the checkpoints in path `DeepPATH/DeepPATH_code/example_TCGA_lung/checkpoints/`, all of them only contain meta file and index file but the data file containing model weights is missing. 
Is it still possible to load the weights used in the paper after training for evaluation-- If yes, can you point me how to? or is it that the checkpoints are dummy and serve only as a purpose to be able to run the pipeline? 

When I try to load the model, it says `run1a_3D_classifier/model.ckpt-69000.data-00000-of-00001; No such file or directory`

**Comment by ncoudray** [comment]
Hi,

  Indeed, the missing file is to big to be shared via github. Please email me an invit to a shared box/folder and I'll upload them there

Best,
Nicolas

**Comment by andanison** [comment]
Hi Nicolas

Thank you for your quick reply.
I couldn't find your email to send you an invite so created a public link
where you can upload :

https://polybox.ethz.ch/index.php/s/5Uw8y97fk6Uj3rS

Let me know in case it doesn't work. If you prefer an invite via email,
please let me know your email address that I can use.

Kind regards
Sonali

**Comment by ncoudray** [comment]
done

Best
N.

**Comment by afrankel** [comment]
I am trying to do something similar by using transfer learning with the run1a_3D_classifier. I am getting ...run1a_3D_classifier/model.ckpt-69000.data-00000-of-00001; No such file or directory

I suppose I need the same large file.  Also, I noticed that the transfer learning using the inception-v3 checkpoint includes the following files:

- checkpoint 
- model.ckpt-157585

I assume I create my own checkpoint file for run1a_3D_classifier and then the large file I am missing is the equivalent of the model.ckpt-157585 file. Is that correct?

**Comment by ncoudray** [comment]
Hi - Yes, one of the files is too big to be shared on github, but if you send me an invit on box, I can drop them there for you

**Comment by afrankel** [comment]
https://www.dropbox.com/request/YLVtInDEH54kaAhe1436

Hopefully, that works and has enough space.
Thank you!

**Comment by ncoudray** [comment]
did it - let me know if you got them

**Comment by afrankel** [comment]
Thank you

**Comment by fredafredaf** [comment]
Hi Nicholas, 

I am trying to do perform mutation transfer learning with the run1b_10way_MutationClassifier, could you please share with me the .data file? thank you. 

https://drive.google.com/drive/folders/1_Urcuw9i3U8EPMAhG3EQ2Gl33N1mJwvn?usp=sharing

**Comment by ncoudray** [comment]
Hi Fred - 
Done.
HTH
