### ISSUE TITLE
Tiling - can result in high FP?

### ISSUE THREAD

**Issue by ratanman** [ncoudray/DeepPATH#62]
When creating tiles (using TCGA metadata) into separate class folder names won't there be tiles having no cancerous cells? This could result in high False Positives. How is this issue solved? 
If using annotated data dividing into tiles then each tile should also be associated with correct annotations. How is this achieved?

**Comment by ncoudray** [comment]
Hi,
  Yes. In TCGA though, the percentage of tumor is really high, so the proportion of normal is low and doesn't seem to impact the overall classification of the slide after aggregation.
If not the case, you can first annotate the slide with ImageScope for example and then use the generated xml file with the different ROIs labeled as input per-tile labels.
HTH,
Best,
Nicolas
