### ISSUE TITLE
UnboundLocalError: local variable 'HeatMap_divider' referenced before assignment

### ISSUE THREAD

**Issue by weizhenFrank** [ncoudray/DeepPATH#64]
Thanks for your great work of DeepPATH, and I want to use the 0f_HeatMap_nClasses.py to generate the heatmap, however, I got the error "UnboundLocalError: local variable 'HeatMap_divider' referenced before assignment". And my input file is the same structure as your "out_filename_Stats.txt". and my  “ directory_to_jpeg_classes” is a directory composed of two sub-directory which are two classes with the jpeg files in the sub-directory. Could you do me a favor? 
[NewestTestDataSetStat.txt](https://github.com/ncoudray/DeepPATH/files/4360286/NewestTestDataSetStat.txt)

**Comment by ncoudray** [comment]
Hi - 
can you please update the code to make sure you have the latest version of the code on github, then try again?
Also, if you do not use any slide or tile filter, specify it in the input options with two single quotes (so empty field)
( --slide_filter '' --filter_tile '')

**Comment by weizhenFrank** [comment]
> Hi -
> can you please update the code to make sure you have the latest version of the code on github, then try again?
> Also, if you do not use any slide or tile filter, specify it in the input options with two single quotes (so empty field)
> ( --slide_filter '' --filter_tile '')

Thanks for your reply. I am so sorry for my unclear statement. My code is totally same with the code of ""DeepPATH/DeepPATH_code/03_postprocessing/0f_HeatMap_nClasses.py" and as I use my own custom dataset, my command is as followings:
python 0f_HeatMap_nClasses.py --image_file '/p300/RenJiData/test' --tiles_overlap 0 --output_dir 'result_folder' --tiles_stats '/p300/NewestTestDataSetStat.txt' --resample_factor 10 --slide_filter '2019-11-11_25954' --filter_tile '' --Cmap 'CancerType' --tiles_size 256. And I realize that I need to put all the images in one folder. And I do that, then I run the same command. And the error changed "sub_dirs:
[]
Traceback (most recent call last):
  File "0f_HeatMap_nClasses.py", line 557, in <module>
    main()
  File "0f_HeatMap_nClasses.py", line 342, in main
    if isError == False:
UnboundLocalError: local variable 'isError' referenced before assignment
(py3.5) 
" My python is 3.5 and package is same as yours.

**Comment by ncoudray** [comment]
Indeed - There is a typo in "IsError = True". Thanks for reporting it.

**Comment by ncoudray** [comment]
OK - there is a typo in isError which is written IsError at some point.


Thanks for mentioning it/


Best,

N.



________________________________
