### ISSUE TITLE
missing checkpoint data file

### ISSUE THREAD

**Issue by RJieInGit** [ncoudray/DeepPATH#66]
Hello 
     I am a graduate student at Syracuse University.  Our team is working on a DL class project to connect Deep learning with disease diagnosis.
     Your work is very inspiring to us but it seems that the checkpoint data file is missing.  Unfortunately, we don't have enough computing power to retrain the model for 400k iteration. Would you mind sharing the checkpoint data with us for study purposes?

https://www.dropbox.com/request/igSH0wxH46VhrEboxyqz
I create a dropbox upload link here, I will be very grateful if you can share it with us.

**Comment by ncoudray** [comment]
Hi - 
Done - these are the checkpoints related to example in example_TCGA_lung folder.

Best,
N.
