### ISSUE TITLE
Mutation Prediction Data duplication

### ISSUE THREAD

**Issue by SuzTulip** [ncoudray/DeepPATH#69]
Hi,
We are working on mutation prediction using 10 class sigmoid classifier and have few queries regarding the tile sorting. Forgive me if it seems trivial:
Going through your code and the repo we got that- A particular TGCA ID can have more than one mutation and thus in label file generated there will be multiple entries for it. And when sorting into 10 folders, the same tile will be assigned to one or more folder based on the number of different gene mutations it is associated it. Won't it lead to duplication of tiles across classes and affect the learning process and weight updation during back propagation? The same tile might change weights in a certain way when processed for a particular class of gene and then again when processed as a part of a different class change the weights in such a way the previous changes might be undone?
Does having more data prevent this?

Thanks in advance, 
Suzanne

**Comment by ncoudray** [comment]
Hi Suzanne,

 For multi-class option, the class assignment is actually done during the conversion to TFRecord (section 0.3b). Each tile is assigned a vector and each cell of the vector corresponds to the mutation status of the corresponding gene. For more details, you can also see the example in:
https://github.com/ncoudray/DeepPATH/tree/master/DeepPATH_code/example_TCGA_lung

  For mutations, we can favor binary classifications which are easier to deal with. Example at the end of this thread:
https://github.com/ncoudray/DeepPATH/issues/37#issuecomment-532725200

Best,
Nicolas
