### ISSUE TITLE
Number of LUAD, LUSC and Normal images

### ISSUE THREAD

**Issue by Reasat** [ncoudray/DeepPATH#70]
Hello 
I have a question regarding the number of .svs files used per LUAD, LUSC, and normal class.
The paper says the numbers are LUAD --> 567, LUSC --> 609, and normal --> 459
But on the  [github page](https://github.com/ncoudray/DeepPATH/tree/master/DeepPATH_code/example_TCGA_lung) numbers are different, LUAD --> 823, LUSC --> 753, and normal --> 591. 

Why did the numbers change?

Thanks!

**Comment by ncoudray** [comment]
Hi - The paper was based on images we were able to download a while ago from the legacy website. On the website, we used the full dataset we were able to download from the latest GDC-TCGA website.
Best

**Comment by NotF404** [comment]
Hi Nicolas,

I have a question regarding to this issue. The number of LUAD slides is 567(403+85+79) in LUAD vs LUSC classification, while it's 382(320+62) in Gene mutation prediction. Is it just caused by removing the diagnostic slides(FFPE slides)，rights?

Best

**Comment by ncoudray** [comment]
Hi,
 we only used Frozen slides indeed, not FFPE.
 You may want to look at the updated example [page](
https://github.com/ncoudray/DeepPATH/tree/master/DeepPATH_code/example_TCGA_lung) which is using all the frozen slides available on TCGA as of Jan 2020. Note that in step 3.2, when you do the segmentation of the tiles, the function "0d_SortTiles.py" has a "threshold" option that allows you to select all tiles from a given class above a certain threshold. The number of tiles (and slides) included after segmentation can therefore vary depending on your threshold as well

Best
Nicolas
