### ISSUE TITLE
JSON files?

### ISSUE THREAD

**Issue by jamesdiplomat** [ncoudray/DeepPATH#71]
Hi Nicolas,

I am aware that I would need to download the .json metadata files from the TCGA legacy portal, not the harmonized portal - but I believe that this is less preferable than downloading from the TCGA new portal, as the legacy portal is not updated (the images that I need were not present...). Is there a way to either make the downloaded biospecimen, new metadata, and the clinical data combined together so that it's still a viable workaround to the old .json format, or are there any repositories that have used the new data format?

**Comment by jamesdiplomat** [comment]
I am unfortunately unfamiliar with the .json file format, so it's hard for me to operate with them... and with the more than 800 lines in the 0d_SortTiles.py, I unfortunately do not understand how to create a workaround... thanks

**Comment by ncoudray** [comment]
Hi - There are two solution I can think of
1- you can try to modify the code (lines 395-401 / 39-52 depending on the option you need)
2- convert json to csv (there are online tools) and, then just create a text file with 1st column patient ID, second your label, and use option 14

HTH
Best,
Nicolas

**Comment by jamesdiplomat** [comment]
Hi Nicolas, I am considering writing my own sorting engine using the clinical, biospecimen, and metadata TSVs. What should I be aware of if I write one myself, like not putting tiles from the same SVS image across both the training and the validation datasets?

**Comment by ncoudray** [comment]
Yes, you will need to check patient's IDs to make sure slides form a given patient go to the same set. 

Re the labels, I'm not 100% sure. It's safer to always double check everything

**Comment by jamesdiplomat** [comment]
I really don't know what is happening here with an error sticking out on line 404, as I tried many options over many hours: this is because I don't understand what was referred to when you said patientID when there is none in any of the .json or .tsv files that I downloaded from TCGA:

Here is my command:
`jfang@jfang-workstation:~/fastai/data/tcga_experiment/images/sorted$ python ../../DeepPATH/DeepPATH_code/00_preprocessing/0d_SortTiles_v2.py --SourceFolder='../456px_Tiles_50Bkg/' --Magnification=20.0  --MagDiffAllowed=0 --SortingOption=14  --PatientID=12 --nSplit 0 --JsonFile='/home/jfang/Documents/tcga_labels.csv' --PercentTest=0 --PercentValid=15`

And here is the error:
`Traceback (most recent call last):
  File "../../DeepPATH/DeepPATH_code/00_preprocessing/0d_SortTiles_v2.py", line 404, in <module>
    jdata[tmp_PID] = line.split()[1]
IndexError: list index out of range`

Here is the sample_sheet (in .txt format, because Github doesn't allow me to attach files in .tsv format), from which I got my (supposedly) ID:

[gdc_sample_sheet.2020-06-19.txt](https://github.com/ncoudray/DeepPATH/files/4833929/gdc_sample_sheet.2020-06-19.txt)

And here is the tcga_labels.csv (again in .txt format because that's what github accepts) that I've made:

[tcga_labels.txt](https://github.com/ncoudray/DeepPATH/files/4833933/tcga_labels.txt)

what am I doing wrong here? how should I proceed with sorting option number 14, and can you give me an example file of what the right file looks like? because frankly I don't know what is meant by patientID.

**Comment by ncoudray** [comment]
in your tcga_labels.txt file, you do not use the patient ID. Also, label file does not have header and columns are space or tab separated.
For a ID of 12, it would look like:
TCGA-55-8204 TCGA-LUAD
TCGA-05-5420 TCGA-LUAD
....

see https://github.com/ncoudray/DeepPATH/blob/master/DeepPATH_code/example_TCGA_lung/labels_r3.txt for an example

HTH
Nicolas
