### ISSUE TITLE
Testing the model produces different results without changing data for classes

### ISSUE THREAD

**Issue by afrankel** [ncoudray/DeepPATH#73]
Let me provide the scenario I'm running into:

I have a model with a checkpoint and I'm running nc_imagenet_eval.py on my test data. Let's say I have 3 labels - Class1, Class2, and Class3.
I have run two different scenarios:
- Scenario 1 where there is test data for Class1, Class2, and Class3
- Scenario 2 where is there is exactly the same test data as Scenario 1 (TFRecords) for Class2 and Class3 only - with no test data for Class1.

I would have assumed that the results for Class2 and Class3 would be the same for both scenarios, but they are not. 

As mentioned here in question 3: https://github.com/ncoudray/DeepPATH/issues/32  I see the same duplication in out_filename_Stats.txt and also a different number of duplicated records for my scenario 1 and 2 and wondering if that has an impact.

My results for Scenario 1:
out2_roc_data_AvPb_c1auc_1.0000_CIs_1.0000_1.0000_t0.943595.txt
out2_roc_data_AvPb_c2auc_0.7538_CIs_0.5636_0.9006_t0.431183.txt
out2_roc_data_AvPb_c3auc_0.7152_CIs_0.5131_0.8810_t0.599621.txt

My results for Scenario 2:
out2_roc_data_AvPb_c1auc_nan_CIs_0.0000_0.0000_t0.000000.txt
out2_roc_data_AvPb_c2auc_0.6800_CIs_0.4632_0.8633_t0.431183.txt
out2_roc_data_AvPb_c3auc_0.6867_CIs_0.4700_0.8718_t0.599621.txt

Since I removed Class1's data (TFRecords) from Scenario 2's test, the result of 0 is what I expected and received, but I was surprised at the different results (for AUC) for Class2 and Class3 given that the same exact TFRecords were used for Class2 and Class3 in both scenario 1 and 2. My labels file is the same in both scenarios (with Class1, Class2, and Class3).

Can you explain my results?

**Comment by ncoudray** [comment]
Hi - 

  We used the scikit-learn multiclass code to compute the ROC/AUC. You may want to have a look here:
https://scikit-learn.org/stable/auto_examples/model_selection/plot_roc.html

 So for each class, the ROC is computed using all data of the considered class vs all other classes. In the second case, you use less data to run the estimate of class 2 vs class 3 instead of class 2 vs class 1&3

**Comment by afrankel** [comment]
Thank you. That makes sense.
