### ISSUE TITLE
Hi:The data set link you provided shows that it cannot be accessed. Could you provide a link again?Thank you very much! Looking forward to hearing from you!

### ISSUE THREAD

**Issue by lsm-sunny** [ncoudray/DeepPATH#74]

**Comment by ncoudray** [comment]
Hi - I'm not sure I understand what link you're talking about. Can you be more specific please?
N.

**Comment by lsm-sunny** [comment]
Sorry, the question I asked before is not clear. How can I find the data set used in this experiment? And https://gdc-portal.nci.nih.gov is not accessible

**Comment by ncoudray** [comment]
This is the gdc website:
https://portal.gdc.cancer.gov/
Best,
N.

**Comment by lsm-sunny** [comment]
Thank you very much for your reply, but I still don’t know how to download the data set required for this experiment, and the link you replied is not accessible. Thank you very much.
