### ISSUE TITLE
model.ckpt-81500.data-00000-of-00001

### ISSUE THREAD

**Issue by ccchen-ccc** [ncoudray/DeepPATH#75]
Hi,

We are working on mutation prediction using 10 class sigmoid classifier and would like to test your trained model. Please forgive me for making this request:

We encountered this error “model.ckpt-81500.data-00000-of-00001; No such file or directory”，
Can you provide such a parameter file? We guarantee that it is only used as a test reference.

Thanks in advance,
ccchen

**Comment by ncoudray** [comment]
Hi -

 yes, those are too big to share via github, but if you share some endpoint (dropbox for example), I can share them with you

Best,
Nicolas

**Comment by ccchen-ccc** [comment]
Hi,

This is my dropbox account (chencongcong01@gmail.com). Thank you for your warm response!!

Best regards
ccchen

**Comment by ccchen-ccc** [comment]
> Hi -
> 
> yes, those are too big to share via github, but if you share some endpoint (dropbox for example), I can share them with you
> 
> Best,
> Nicolas

Dear Nicolas

I feel sorry to disturb you again. At your convenience, would you please send me the file ‘model.ckpt-***.data-00000-of-00001’？Can the parameter file be shared through the dropbox account (chencongcong01@gmail.com) I provided？ Or can it be sent by e-mail (chencongcong01@163.com)? Thank you for your assistance.

Best regards
ccchen

**Comment by qwang-big** [comment]
Dear Nicolas

I'm also in need of the model file as I'm working on the project which requires the intepretation of the slide images, but cannot afford the training time. Would you please also share the model with me? Thanks!

Best regards
QW

**Comment by ncoudray** [comment]
Hi Qwang,

  same, share with me some endpoint on your dropbox where I can upload the files

Best,
Nicolas

**Comment by qwang-big** [comment]
> Hi Qwang,
> 
> same, share with me some endpoint on your dropbox where I can upload the files
> 
> Best,
> Nicolas

Hi Nicolas,

thank you very much for your reply. Could you upload to google drive? You can also use mine if you don't have one. There is 15G free storage for everyone. Please write to me (qwang.big@gmail.com) regarding to the uploading issues. 

Best,
Qwang

**Comment by luciantunez** [comment]
could you send me the pretrained model also? to luantunez95@gmail.com
thank you very much!

**Comment by ncoudray** [comment]
Hi - you need to send me a link to a shared dropbox or drive with enough space that belongs to you.
Best
N.

**Comment by luciantunez** [comment]
https://drive.google.com/drive/u/2/folders/10ZlBl1VNkLlHJN6e9HWEMjfCrge94ORI
thank you!
