### ISSUE TITLE
A question about the dataset

### ISSUE THREAD

**Issue by Ljiaqii** [ncoudray/DeepPATH#77]
Hi，
The experiment used three kinds whole-slide images(LUAD,LUSC and the normal)，but I can not find the normal whole-slide images from the TCGA.Could you tell me how to get them?And without  the normal whole-slide images ,can this experiment be carried out?
Looking forward to your reply。
Best!

**Comment by ncoudray** [comment]
Hi -
 it depends which ones you downloaded. Frozen samples have normal slides, but diagnostic FFPE do not. We used the frozen in our initial study.

Best
