### ISSUE TITLE
Choosing reference image for Vahadane normalization

### ISSUE THREAD

**Issue by bajajsweta** [ncoudray/DeepPATH#78]
Hi @ncoudray,

I am working on using the vahadane normalization and i don't seem to understand where and how have you chosen the reference image? I read the paper and didn't find it there too. Was there any criteria or selection process in place.
I apologize if its already there and I've missed it somewhere. 

Thank you for your time.
Best,
Sweta

**Comment by ncoudray** [comment]
Hi Sweta,

 Sorry, I don't have any trick to select it. We just selected one representative image

Best,
Nicolas

**Comment by bajajsweta** [comment]
Thank you for getting back to me @ncoudray.
