### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by sahilkhose** [ncoudray/DeepPATH#79]
"Create and download a manifest and metadata json file from the gdc website for the whole slides images of interest"
What exactly do we have to search for the manifest and metadata files on https://portal.gdc.cancer.gov/ ? (TCGA-LUAD TCGA-LUSC and what else? Also what to download after that? Biospecimen? Clinical? Manifest?)
Also on the https://portal.gdc.cancer.gov/ website from over a month it is mentioned that "Attention GDC Users: All slide and diagnostics images from the TCGA program are currently unavailable for download" 
And still if I search TCGA-LUAD the manifest downloading option works.

**Comment by gabrieldernbach** [comment]
It seems the manifest file in https://github.com/ncoudray/DeepPATH/tree/master/DeepPATH_code/example_TCGA_lung can be used with the tcga cli download tool. However the portal is still not available.

I contacted the TCGA support team, but they could not give any estimate on when it will be back online. They - quote - "hope to have an update within the next few weeks"

In the mean time, @ncoudray should have a mirror of the data. May I kindly ask for making it available? 
Kind regards

**Comment by ncoudray** [comment]
Hi - You will need to create a globus endpoint and grant me writing access to it. It is the most convenient way on our side to transfer the TCGA data we have for the time being

**Comment by gabrieldernbach** [comment]
@ncoudray I went through the globe registration/installation/setup and read the docs. Although I can create a personal endpoint, I can only grand writing access to other users once it is set as shared, which again requires it to be managed, which again requires a subscription. I signed up for a trial and will contact you once they come back to me.

If your institution has a subscription running already, sharing may be easier on your side. If you like we can switch this conversation to mail. I couldn't find your address, but you can reach me via gabriel.dernbach@charite.de

**Comment by sahilkhose** [comment]
I would like to be in the thread if you're shifting this to email. sahilkhose18@gmail.com

**Comment by sahilkhose** [comment]
Are there any updates?

**Comment by gabrieldernbach** [comment]
Nicolas and I managed to transfer the files, which took a bit of effort because of strong security demands on both sides (as they are typical for public research clusters).
I got that Nicolas is already on vacation, and I will be for the next two weeks. I am happy to share the data but this will have some delay, sorry for that.

**Comment by sahilkhose** [comment]
Sure! Let me know the procedure for the transfer as soon as possible.
