### ISSUE TITLE
About retrieve mutation information: "the barecode can be used to match images to sample."

### ISSUE THREAD

**Issue by agentdr1** [ncoudray/DeepPATH#88]
Hi, 

I am working on a similar mutation prediction task (TCGA colon) and closely follow your readme (3.1 - Retrieve mutation information). I have the WSIs, the related manifest file and also the MAF file as described in 3.1; you wrote: _"and the barecode can be used to match images to sample. "_ 
Which barcode, or in other words IDs do you use for the slides and which IDs from the MAF file to match them? 

Best regards, 
Daniel

**Comment by ncoudray** [comment]
Hi Daniel,

  The first 12 digits of the image name (TCGA-##-####); you can check https://docs.gdc.cancer.gov/Encyclopedia/pages/TCGA_Barcode/ for barecode explanations.

Best,
Nicolas

**Comment by agentdr1** [comment]
That was exactly what I need, thanks for the quick reply!
