### ISSUE TITLE
Downsampling for low magnification tiles

### ISSUE THREAD

**Issue by mitchellwiebe** [ncoudray/DeepPATH#92]
Hi there,

In reference to ''0b_tileLoop_deepzoom4.py'' - I'm trying to understand how downsampling is performed when tiling svs slides at low magnification. For example, tiling a slide at its native resolution of 20x (0.5 microns/px) requires no downsampling, but tiling the same slide at 5x would require some form of downsampling. My reason for asking is that I would like to have a better idea of the spatial resolution in low magnification tiles (5x and below). From what I expect, 5x tiles should have a spatial resolution around 2 microns/px, but I would like to be more confident in this assumption. 

Thank you,
Mitch

**Comment by ncoudray** [comment]
Hi Mitch,

  Yes, correct, 5x is four times larger, so it will contain the equivalent of 16 20x tiles (4x4), so pixelsize would be 4x0.5 um /px.
  (Note, the svs have the exact pixel size in the header. There are slight variations depending on the scanners used)

Best,
Nicolas
